name: matharena
description: "A competitive multiplayer mobile game focused on ranked mathematics."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  math_expressions: ^2.5.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.0
  json_serializable: ^6.7.1
  custom_lint: ^0.5.0
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true